### PR TITLE
Fix T244489: Break out static lists from ahotts_adapter.py

### PR DESCRIPTION
**Pull request by e-gor**
Fix T244489: Break out static lists from ahotts_adapter.py

[https://phabricator.wikimedia.org/T244489](https://phabricator.wikimedia.org/T244489)

### CODE REVIEW

**Comment by lokal-profil** [comment]
@HannaLindgren has the `ahotts-merge` branch been merged into master already? If so could you @e-gor re-base this on master?

Since the broken out bits are "just" static lists it would probably make more sense to have them as json or yaml files or similar rather than python files.

**Comment by HannaLindgren** [comment]
> @HannaLindgren has the `ahotts-merge` branch been merged into master already? If so could you @e-gor re-base this on master?
> 
> Since the broken out bits are "just" static lists it would probably make more sense to have them as json or yaml files or similar rather than python files.

Yes, the ahotts-merge branch has been merged into master. So it would indeed make sense to make the changes based on the master branch, yes.

**Comment by HannaLindgren** [comment]
[cc @lokal-profil] @e-gor, could you make a new pull request based on the master branch instead?

**Comment by e-gor** [comment]
Done, closing this PR.

**Pull request closed without merging**
